-- 002: no-login privilege groups; login passwords are provisioned separately.
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'f1_app_reader') THEN CREATE ROLE f1_app_reader NOLOGIN; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'f1_ingestor') THEN CREATE ROLE f1_ingestor NOLOGIN; END IF;
END $$;
REVOKE ALL ON SCHEMA f1, f1_ingest FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA f1, f1_ingest FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA f1, f1_ingest FROM PUBLIC;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA f1_ingest FROM PUBLIC;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
DO $$ BEGIN EXECUTE format('REVOKE TEMPORARY ON DATABASE %I FROM PUBLIC', current_database()); END $$;
GRANT USAGE ON SCHEMA f1 TO f1_app_reader;
GRANT SELECT ON ALL TABLES IN SCHEMA f1 TO f1_app_reader;
GRANT USAGE ON SCHEMA f1, f1_ingest TO f1_ingestor;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA f1 TO f1_ingestor;
GRANT SELECT, INSERT ON f1_ingest.source_payloads, f1_ingest.source_records TO f1_ingestor;
GRANT SELECT, INSERT, UPDATE ON f1_ingest.ingestion_runs TO f1_ingestor;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA f1 TO f1_ingestor;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA f1_ingest TO f1_ingestor;
-- These defaults apply to tables created by the migration owner, not arbitrary roles.
ALTER DEFAULT PRIVILEGES IN SCHEMA f1 GRANT SELECT ON TABLES TO f1_app_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA f1 GRANT SELECT, INSERT, UPDATE ON TABLES TO f1_ingestor;
ALTER DEFAULT PRIVILEGES IN SCHEMA f1 GRANT USAGE ON SEQUENCES TO f1_ingestor;
ALTER DEFAULT PRIVILEGES IN SCHEMA f1_ingest REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
